[package]
name = "koto_test_utils"
version = "0.14.0"
edition = "2021"
authors = ["irh <ian.r.hobson@gmail.com>"]
license = "MIT"
description = "Testing utilities for the Koto programming language"
homepage = "https://koto.dev"
repository = "https://github.com/koto-lang/koto"
keywords = ["scripting", "language", "koto"]

[dependencies]
koto_bytecode = { path = "../bytecode", version = "^0.14.0" }
koto_runtime = { path = "../runtime", version = "^0.14.0" }

pulldown-cmark = { workspace = true }
