[workspace]
members = [
  "src/bytecode",
  "src/cli",
  "src/json",
  "src/koto",
  "src/lexer",
  "src/parser",
  "src/random",
  "src/runtime",
  "src/serialize",
  "src/toml",
  "src/types",
]

[profile.dev]
opt-level = 0
