[package]
name = "kotoapp"

version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "koto"
]

[dependencies]
koto = { path = "koto" }
pest = "2.1.2"
pest_derive  = "2.1.0"

[dependencies.clap]
version = "2.33.0"
# default-features = false
