[package]
name = "koto_runtime"
version = "0.10.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"
license = "MIT"
description = "The runtime used by the Koto programming language"
homepage = "https://github.com/koto-lang/koto"
repository = "https://github.com/koto-lang/koto"
keywords = ["scripting", "language", "koto"]

[features]
default = []
panic_on_runtime_error = []

[dependencies]
koto_bytecode = { path = "../bytecode", version = "^0.10.0"}
koto_lexer = { path = "../lexer", version = "^0.10.0"}
koto_parser = { path = "../parser", version = "^0.10.0"}

downcast-rs = "1.1.1"
indexmap = "1.4.0"
rustc-hash = "1.1.0"
smallvec = "1.2.0"
unicode-segmentation = "1.7.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = "0.4.19"
instant = "0.1.12"

[target.'cfg(target_arch = "wasm32")'.dependencies]
chrono = {version = "0.4.19", features = ["wasmbind"]}
instant = {version = "0.1.12", features = ["wasm-bindgen"]}
