[package]
name = "koto_runtime"
version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

[features]
default = []
trace = []
panic_on_runtime_error = []

[dependencies]
downcast-rs = "1.1.1"
indexmap = "1.4.0"
koto_bytecode = { path = "../bytecode" }
koto_parser = { path = "../parser" }
rustc-hash = "1.1.0"
smallvec = "1.2.0"
