[package]
name = "koto"
version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

[features]
default = []
trace = []
panic_on_runtime_error = []

[dependencies]
koto_parser = { path = "../parser" }
rustc-hash = "1.1.0"
vec1 = "1.4.0"

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "koto_benchmark"
harness = false
