[package]
name = "koto"
version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

[features]
default = []
trace = ["koto_runtime/trace"]
panic_on_runtime_error = ["koto_runtime/panic_on_runtime_error"]

[dependencies]
koto_bytecode = {path = "../bytecode"}
koto_parser = {path = "../parser"}
koto_runtime = {path = "../runtime"}

[dev-dependencies]
koto_json = {path = "../../libs/json" }
koto_random = {path = "../../libs/random" }
koto_toml = {path = "../../libs/toml" }

criterion = "0.3.1"

[target.'cfg(not(target_env = "msvc"))'.dev-dependencies]
jemallocator = {version = "0.3.2"}

[[bench]]
name = "koto_benchmark"
harness = false
