[package]
name = "koto"
version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

[features]
default = []
trace = []

[dependencies]
koto_parser = { path = "../parser" }
hashbrown = "0.7.0"

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "koto_benchmark"
harness = false
