[package]
name = "koto_cli"

version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

[[bin]]
name = "koto"
path = "src/main.rs"

[features]
default = []
trace = ["koto/trace"]
jemalloc = ["jemallocator"]

[dependencies]
koto = {path = "../koto"}
koto_json = {path = "../../libs/json"}
koto_random = {path = "../../libs/random"}
koto_tempfile = {path = "../../libs/tempfile"}
koto_toml = {path = "../../libs/toml"}

termion = "1.5.5"

[dependencies.pico-args]
version = "0.3.4"
default-features = false

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = {version = "0.3.2", optional = true}
