[package]
name = "koto_cli"

version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

[[bin]]
name = "koto"
path = "src/main.rs"

[features]
default = []
trace = ["koto/trace"]

[dependencies]
koto = {path = "../koto"}
koto_json = {path = "../../libs/json"}
koto_random = {path = "../../libs/random"}
koto_toml = {path = "../../libs/toml"}

termion = "1.5.5"

[dependencies.clap]
version = "3.0.0-beta.1"
default-features = false
features = ["std"]

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = {version = "0.3.2"}
