[package]
name = "koto_bytecode"
version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
koto_parser = { path = "../parser" }
num_enum = "0.4.3"
smallvec = "1.2.0"
