[package]
name = "koto_std"
version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

[dependencies]
koto_lexer = { path = "../lexer" }
koto_parser = { path = "../parser" }
koto_runtime = { path = "../runtime" }
koto_serialize = { path = "../serialize" }

tempfile = "3.1.0"
