[package]
name = "koto_std"
version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

[dependencies]
koto_runtime = { path = "../runtime" }
koto_types = { path = "../types" }

rand = "0.7.3"
rand_chacha = "0.2.1"
