name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --all-targets --verbose

      - name: Run tests
        run: cargo test --all-targets --verbose

      - name: Run poetry example
        run: cargo run --example poetry -- -s examples/poetry/scripts/readme.koto

  fmt_and_clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features

  wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: v0.9.1

      - name: Build wasm example
        run: cd examples/wasm && wasm-pack build
